// Autogenerated Background Worker for FilterManager Effects
const vals = {};
/** Mock document avant tout importScripts (évite TDZ avec image-adjust-core.js). */
var document = {
    getElementById: function (id) {
        if (vals[id] !== undefined) return { value: vals[id] };
        return null;
    },
    createElement: function (tag) {
        if (tag === 'canvas') return new OffscreenCanvas(10, 10);
        return null;
    }
};

(function () {
    'use strict';
    const workerDir = (function () {
        const p = String(self.location.pathname || '');
        const i = p.lastIndexOf('/');
        return i >= 0 ? p.slice(0, i + 1) : '/';
    })();
    function illuWorkerImport(rel) {
        try {
            const url = new URL(rel, self.location.href).href;
            importScripts(url);
        } catch (e) {
            const path = String(rel || '').replace(/^\//, '');
            const url = path.startsWith('http') ? path : workerDir + path;
            importScripts(url);
        }
    }
    const deps = [
        'photo-pipeline.js',
        'radial-zoom-blur.js',
        'ral_colors.js',
        'ChromaKeyer.js',
        'vhs-core.js',
        'halftone-core.js',
        'image-adjust-core.js',
        'pdn-effects.js'
    ];
    for (let i = 0; i < deps.length; i++) {
        try {
            illuWorkerImport(deps[i]);
        } catch (e) {
            console.warn('[filter-worker] import failed:', deps[i], e);
        }
    }
    try {
        illuWorkerImport('../WasmManager.js');
    } catch (e) {
        console.warn('[filter-worker] WasmManager.js optional load failed', e);
    }
})();

let currentImageData = null;
let currentCtx = {
    imageSmoothingEnabled: true,
    imageSmoothingQuality: 'low',
    putImageData: function(imgd, x, y) {
        currentImageData = imgd;
    },
    clearRect: function(x, y, w, h) {
        // No-op
    },
    save: function() {}, restore: function() {}, translate: function() {}, scale: function() {}, shadowColor: '', shadowBlur: 0, shadowOffsetX: 0, shadowOffsetY: 0,
    drawImage: function(cv, sx, sy, sw, sh, dx, dy, dw, dh) {
        try {
            let targetW = (sw !== undefined && dw !== undefined) ? dw : (sw !== undefined ? sw : cv.width);
            let targetH = (sh !== undefined && dh !== undefined) ? dh : (sh !== undefined ? sh : cv.height);
            const tempCtx = new OffscreenCanvas(targetW, targetH).getContext('2d');
            if (sh !== undefined && dh !== undefined) tempCtx.drawImage(cv, sx, sy, sw, sh, dx, dy, dw, dh);
            else if (sw !== undefined) tempCtx.drawImage(cv, sx, sy, sw, sh);
            else tempCtx.drawImage(cv, sx, sy);
            currentImageData = tempCtx.getImageData(0, 0, targetW, targetH);
        } catch (e) {
            console.error('Worker drawImage error:', e);
        }
    }
};

const FilterManager = {
    originalImageData: null,
    currentEffect: null,
    _cabossageSeed: 0x9e3779b9,
    _grainSeed: 0x2b7e1516,
    ctx: currentCtx,
    _effectPreviewPxScale: 1,
    _margin: 0,
    _startY: 0,
    _endY: 0,

    reportProgress(percent, label) {
        if (this._jobId) {
            self.postMessage({
                type: 'progress',
                jobId: this._jobId,
                percent: percent,
                message: label + ' (' + percent + '%)'
            });
        }
    },

    _sampleBilinear(src, w, h, x, y) {
        if (x < 0) x = 0; if (y < 0) y = 0;
        if (x >= w - 1) x = w - 1 - 1e-6; if (y >= h - 1) y = h - 1 - 1e-6;
        const x0 = Math.floor(x), y0 = Math.floor(y);
        const x1 = x0 + 1, y1 = y0 + 1;
        const tx = x - x0, ty = y - y0;
        const idx = (yy, xx) => (yy * w + xx) * 4;
        const lerp = (a, b, t) => a + (b - a) * t;
        const i00 = idx(y0, x0), i10 = idx(y0, x1), i01 = idx(y1, x0), i11 = idx(y1, x1);
        const ch = (o) => lerp(lerp(src[i00 + o], src[i10 + o], tx), lerp(src[i01 + o], src[i11 + o], tx), ty);
        return [ch(0), ch(1), ch(2), ch(3)];
    },

    _grainNoise(ix, iy) {
        let n = Math.imul(ix | 0, 1597334677) + Math.imul(iy | 0, 3812015801) + (this._grainSeed >>> 0);
        n = (n ^ (n >>> 15)) >>> 0;
        return (n / 4294967296) * 2 - 1;
    },

    _parseHexColor(hex) {
        const h = String(hex || '').replace('#', '').trim();
        if (h.length !== 6) return { r: 0, g: 0, b: 0 };
        const n = parseInt(h, 16);
        if (Number.isNaN(n)) return { r: 0, g: 0, b: 0 };
        return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255 };
    },

    rgbToHsv(r, g, b) {
        r /= 255; g /= 255; b /= 255;
        let max = Math.max(r, g, b), min = Math.min(r, g, b);
        let h = 0, s = 0, v = max, d = max - min;
        s = max === 0 ? 0 : d / max;
        if (max !== min) {
            switch (max) {
                case r: h = (g - b) / d + (g < b ? 6 : 0); break;
                case g: h = (b - r) / d + 2; break;
                case b: h = (r - g) / d + 4; break;
            }
            h /= 6;
        }
        return { h: Math.round(h * 360), s: Math.round(s * 100), v: Math.round(v * 100) };
    },

    hsvToRgb(h, s, v) {
        let r, g, b, i, f, p, q, t;
        h /= 360; s /= 100; v /= 100;
        i = Math.floor(h * 6); f = h * 6 - i;
        p = v * (1 - s); q = v * (1 - f * s); t = v * (1 - (1 - f) * s);
        switch (i % 6) {
            case 0: r = v, g = t, b = p; break;
            case 1: r = q, g = v, b = p; break;
            case 2: r = p, g = v, b = t; break;
            case 3: r = p, g = q, b = v; break;
            case 4: r = t, g = p, b = v; break;
            case 5: r = v, g = p, b = q; break;
        }
        return { r: Math.round(r * 255), g: Math.round(g * 255), b: Math.round(b * 255) };
    },

    rgbToTrueHsl(r, g, b) {
        r /= 255; g /= 255; b /= 255;
        const max = Math.max(r, g, b), min = Math.min(r, g, b);
        let h, s, l = (max + min) / 2;
        if (max === min) { h = s = 0; } else {
            const d = max - min;
            s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
            switch (max) {
                case r: h = (g - b) / d + (g < b ? 6 : 0); break;
                case g: h = (b - r) / d + 2; break;
                case b: h = (r - g) / d + 4; break;
            }
            h /= 6;
        }
        return { h: h * 360, s: s * 100, l: l * 100 };
    },

    hslToTrueRgb(h, s, l) {
        h /= 360; s /= 100; l /= 100;
        let r, g, b;
        if (s === 0) { r = g = b = l; } else {
            const hue2rgb = (p, q, t) => {
                if (t < 0) t += 1; if (t > 1) t -= 1;
                if (t < 1/6) return p + (q - p) * 6 * t;
                if (t < 1/2) return q;
                if (t < 2/3) return p + (q - p) * (2/3 - t) * 6;
                return p;
            };
            const q = l < 1/2 ? l * (1+s) : l + s - l*s;
            const p = 2 * l - q;
            r = hue2rgb(p, q, h + 1/3); g = hue2rgb(p, q, h); b = hue2rgb(p, q, h - 1/3);
        }
        return { r: Math.round(r * 255), g: Math.round(g * 255), b: Math.round(b * 255) };
    },

    getHslWeightsFast(h) {
        if (h < 30) return { i1: 0, i2: 1, w1: 1 - h / 30, w2: h / 30 };
        if (h < 60) return { i1: 1, i2: 2, w1: 1 - (h - 30) / 30, w2: (h - 30) / 30 };
        if (h < 120) return { i1: 2, i2: 3, w1: 1 - (h - 60) / 60, w2: (h - 60) / 60 };
        if (h < 180) return { i1: 3, i2: 4, w1: 1 - (h - 120) / 60, w2: (h - 120) / 60 };
        if (h < 240) return { i1: 4, i2: 5, w1: 1 - (h - 180) / 60, w2: (h - 180) / 60 };
        if (h < 280) return { i1: 5, i2: 6, w1: 1 - (h - 240) / 40, w2: (h - 240) / 40 };
        if (h < 320) return { i1: 6, i2: 7, w1: 1 - (h - 280) / 40, w2: (h - 280) / 40 };
        return { i1: 7, i2: 0, w1: 1 - (h - 320) / 40, w2: (h - 320) / 40 };
    },

    _boxBlurRGBA(rgba, w, h, radius) {
        if (radius < 1) return;
        const tmp = new Uint8ClampedArray(rgba.length);
        const sy = FilterManager._startY || 0, ey = FilterManager._endY || h, margin = FilterManager._margin || 0;
        const safeSy = Math.max(0, sy - margin), safeEy = Math.min(h, ey + margin);
        
        // Horizontal pass must calculate y values expanded by the radius to provide data for the vertical pass
        const horizSy = Math.max(0, safeSy - radius);
        const horizEy = Math.min(h, safeEy + radius);
        for (let y = horizSy; y < horizEy; y++) {
            let r=0,g=0,b=0,a=0,ws=0; const ro = y * w * 4;
            for (let x = -radius; x <= radius; x++) { const ix = Math.max(0, Math.min(w-1, x)); const o = ro + ix*4; r+=rgba[o]; g+=rgba[o+1]; b+=rgba[o+2]; a+=rgba[o+3]; ws++; }
            for (let x = 0; x < w; x++) {
                const i = ro + x*4; tmp[i]=r/ws; tmp[i+1]=g/ws; tmp[i+2]=b/ws; tmp[i+3]=a/ws;
                const iN = ro + Math.min(w-1, x+radius+1)*4, iP = ro + Math.max(0, x-radius)*4;
                r+=rgba[iN]-rgba[iP]; g+=rgba[iN+1]-rgba[iP+1]; b+=rgba[iN+2]-rgba[iP+2]; a+=rgba[iN+3]-rgba[iP+3];
            }
        }
        for (let x = 0; x < w; x++) {
            let r=0,g=0,b=0,a=0,ws=0;
            for (let y = safeSy - radius; y <= safeSy + radius; y++) {
                const o = (Math.max(0, Math.min(h-1, y))*w+x)*4; r+=tmp[o]; g+=tmp[o+1]; b+=tmp[o+2]; a+=tmp[o+3]; ws++;
            }
            for (let y = safeSy; y < safeEy; y++) {
                const i = (y*w+x)*4; rgba[i]=r/ws; rgba[i+1]=g/ws; rgba[i+2]=b/ws; rgba[i+3]=a/ws;
                const iN = (Math.min(h-1, y+radius+1)*w+x)*4, iP = (Math.max(0, y-radius)*w+x)*4;
                r+=tmp[iN]-tmp[iP]; g+=tmp[iN+1]-tmp[iP+1]; b+=tmp[iN+2]-tmp[iP+2]; a+=tmp[iN+3]-tmp[iP+3];
            }
        }
    },

    _solveHomography8(src4, dst4) {
        const A=[]; const b=[]; for(let i=0; i<4; i++){ const [X,Y]=src4[i], [xp,yp]=dst4[i]; A.push([X,Y,1,0,0,0,-X*xp,-Y*xp]); b.push(xp); A.push([0,0,0,X,Y,1,-X*yp,-Y*yp]); b.push(yp); }
        const n=8, M=A.map((row,r)=>[...row,b[r]]);
        for(let col=0; col<n; col++){
            let piv=col; for(let r=col+1; r<n; r++){ if(Math.abs(M[r][col])>Math.abs(M[piv][col])) piv=r; }
            [M[col],M[piv]]=[M[piv],M[col]]; const v=M[col][col]; if(Math.abs(v)<1e-12) return null;
            for(let c=col; c<=n; c++) M[col][c]/=v; for(let r=0; r<n; r++){ if(r===col) continue; const f=M[r][col]; if(f===0) continue; for(let c=col; c<=n; c++) M[r][c]-=f*M[col][c]; }
        }
        const sol=M.map(row=>row[n]); return [sol[0],sol[1],sol[2],sol[3],sol[4],sol[5],sol[6],sol[7],1];
    },
    _invert3x3(m) {
        const [a, b, c, d, e, f, g, h, i] = m;
        const A = e * i - f * h, B = -(d * i - f * g), C = d * h - e * g, D = -(b * i - c * h), E = a * i - c * g, F = -(a * h - b * g), G = b * f - c * e, H = -(a * f - c * d), I = a * e - b * d;
        const det = a * A + b * B + c * C; if (Math.abs(det) < 1e-14) return null;
        const id=1/det; return [A*id, D*id, G*id, B*id, E*id, H*id, C*id, F*id, I*id];
    },
    _quadCorners3D(w, h, rxDeg, ryDeg, focal, zoomScale=1.0) {
        const cx=w/2, cy=h/2, rx=(rxDeg*Math.PI)/180, ry=(ryDeg*Math.PI)/180, f=Math.max(40,focal), d=f*0.55;
        const proj=(sx,sy)=>{ let X=sx-cx, Y=sy-cy, Z=d; const X1=X*Math.cos(ry)+Z*Math.sin(ry), Z1=-X*Math.sin(ry)+Z*Math.cos(ry); X=X1; Z=Z1; const Y2=Y*Math.cos(rx)-Z*Math.sin(rx), Z2=Y*Math.sin(rx)+Z*Math.cos(rx); Y=Y2; Z=Z2; const zz=Math.max(Z,f*0.04); return [f*(X/zz)*zoomScale+cx, f*(Y/zz)*zoomScale+cy]; };
        return [[0,0],[w,0],[w,h],[0,h]].map(([sx,sy])=>proj(sx,sy));
    },
    _pullCorners(quad, w, h, tl, tr, br, bl) {
        const cx=w/2, cy=h/2, am=[tl,tr,br,bl]; return quad.map((p,i)=>{ const k=(am[i]/100)*0.5; return [p[0]+(cx-p[0])*k, p[1]+(cy-p[1])*k]; });
    },

    _cabHash(ix, iy, seed) {
        let n = Math.imul(ix | 0, 374761393) + Math.imul(iy | 0, 668265263) + (seed >>> 0) * 1442695041;
        n = (n ^ (n >>> 13)) >>> 0;
        return (n / 4294967296) * 2 - 1;
    },
    _smoothCabNoise(x, y, cell, seed) {
        const c = Math.max(1.5, cell);
        const x0 = Math.floor(x / c);
        const y0 = Math.floor(y / c);
        const fx = x / c - x0;
        const fy = y / c - y0;
        const u = fx * fx * (3 - 2 * fx);
        const v = fy * fy * (3 - 2 * fy);
        const a = this._cabHash(x0, y0, seed);
        const b = this._cabHash(x0 + 1, y0, seed);
        const cc = this._cabHash(x0, y0 + 1, seed);
        const d = this._cabHash(x0 + 1, y0 + 1, seed);
        return a + (b - a) * u + (cc - a) * v + (a - b - cc + d) * u * v;
    },
    _blurFloatField2D(field, w, h, passes) {
        const tmp = new Float32Array(w * h);
        for (let p = 0; p < passes; p++) {
            for (let y = 0; y < h; y++) {
                for (let x = 0; x < w; x++) {
                    let s = 0;
                    let c = 0;
                    for (let dx = -1; dx <= 1; dx++) {
                        const xx = Math.max(0, Math.min(w - 1, x + dx));
                        s += field[y * w + xx];
                        c++;
                    }
                    tmp[y * w + x] = s / c;
                }
            }
            for (let y = 0; y < h; y++) {
                for (let x = 0; x < w; x++) {
                    let s = 0;
                    let c = 0;
                    for (let dy = -1; dy <= 1; dy++) {
                        const yy = Math.max(0, Math.min(h - 1, y + dy));
                        s += tmp[yy * w + x];
                        c++;
                    }
                    field[y * w + x] = s / c;
                }
            }
        }
    },
    _buildCabossageHeightField(w, h, scaleUi, roughUi, tensionUi, qualityUi, seed) {
        const minD = Math.min(w, h);
        const scale = Math.max(1, Math.min(100, scaleUi));
        const cell = Math.max(2, (minD * (0.08 + ((100 - scale) / 100) * 0.35)) | 0);
        const cellFine = Math.max(1.5, cell * 0.22);
        const rough = Math.max(0, Math.min(100, roughUi)) / 100;
        const H = new Float32Array(w * h);
        let minV = Infinity, maxV = -Infinity;
        for (let y = 0; y < h; y++) {
            for (let x = 0; x < w; x++) {
                const i = y * w + x;
                let v = this._smoothCabNoise(x, y, cell, seed);
                v += rough * this._smoothCabNoise(x + 17.3, y + 91.1, cellFine, seed + 1103515245);
                H[i] = v;
                if(v < minV) minV = v; if(v > maxV) maxV = v;
            }
        }
        const range = maxV - minV;
        if(range > 0) { for(let i=0; i<H.length; i++) H[i] = (H[i] - minV) / range; }
        const tension = Math.max(0, Math.min(100, tensionUi));
        const blurPasses = Math.max(0, Math.round(tension / 4));
        if (blurPasses > 0) this._blurFloatField2D(H, w, h, blurPasses);
        const q = Math.max(1, Math.min(4, Math.round(qualityUi)));
        if (q > 1) this._blurFloatField2D(H, w, h, q - 1);
        return H;
    },

    /* ---- Perlin 2D (port OpenPDN PerlinNoise2D.cs, MIT Ed Harvey) ---- */
    _perlinInit() {
        if (this._perlinLookup) return;
        const perm = [
            151,160,137,91,90,15,131,13,201,95,96,53,194,233,7,225,140,36,103,30,69,142,8,99,37,240,21,10,23,190,6,
            148,247,120,234,75,0,26,197,62,94,252,219,203,117,35,11,32,57,177,33,88,237,149,56,87,174,20,125,136,171,
            168,68,175,74,165,71,134,139,48,27,166,77,146,158,231,83,111,229,122,60,211,133,230,220,105,92,41,55,46,245,
            40,244,102,143,54,65,25,63,161,1,216,80,73,209,76,132,187,208,89,18,169,200,196,135,130,116,188,159,86,
            164,100,109,198,173,186,3,64,52,217,226,250,124,123,5,202,38,147,118,126,255,82,85,212,207,206,59,227,47,
            16,58,17,182,189,28,42,223,183,170,213,119,248,152,2,44,154,163,70,221,153,101,155,167,43,172,9,129,22,39,
            253,19,98,108,110,79,113,224,232,178,185,112,104,218,246,97,228,251,34,242,193,238,210,144,12,191,179,162,
            241,81,51,145,235,249,14,239,107,49,192,214,31,181,199,106,157,184,84,204,176,115,121,50,45,127,4,150,
            254,138,236,205,93,222,114,67,29,24,72,243,141,128,195,78,66,215,61,156,180
        ];
        const lut = new Int32Array(512);
        for (let i = 0; i < 256; i++) { lut[256 + i] = perm[i]; lut[i] = perm[i]; }
        this._perlinLookup = lut;
        const angle = (137.2 / 180.0) * Math.PI;
        this._perlinRot = [Math.cos(angle), -Math.sin(angle), Math.sin(angle), Math.cos(angle)];
    },
    _perlinFade(t) { return t * t * t * (t * (t * 6 - 15) + 10); },
    _perlinGrad(hash, x, y) {
        const h = hash & 15;
        const u = h < 8 ? x : y;
        const v = h < 4 ? y : (h === 12 || h === 14 ? x : 0);
        return ((h & 1) === 0 ? u : -u) + ((h & 2) === 0 ? v : -v);
    },
    _perlinRaw(x, y, seed) {
        const lut = this._perlinLookup;
        const xf = Math.floor(x), yf = Math.floor(y);
        const ix = (xf | 0) & 255, iy = (yf | 0) & 255;
        x -= xf; y -= yf;
        const u = this._perlinFade(x), v = this._perlinFade(y);
        const a = lut[ix + seed] + iy;
        const aa = lut[a & 511], ab = lut[(a + 1) & 511];
        const b = lut[(ix + 1 + seed) & 511] + iy;
        const ba = lut[b & 511], bb = lut[(b + 1) & 511];
        const edge1 = this._perlinLerp(this._perlinGrad(lut[aa & 511], x, y), this._perlinGrad(lut[ba & 511], x - 1, y), u);
        const edge2 = this._perlinLerp(this._perlinGrad(lut[ab & 511], x, y - 1), this._perlinGrad(lut[bb & 511], x - 1, y - 1), u);
        return this._perlinLerp(edge1, edge2, v);
    },
    _perlinLerp(a, b, t) { return a + t * (b - a); },
    /** Variante CloudsEffect : indices entiers + fraction déjà séparés */
    _perlinRaw2(ix, iy, x, y, seed) {
        const lut = this._perlinLookup;
        const u = this._perlinFade(x), v = this._perlinFade(y);
        const a = lut[(ix + seed) & 511] + iy;
        const aa = lut[a & 511], ab = lut[(a + 1) & 511];
        const b = lut[(ix + 1 + seed) & 511] + iy;
        const ba = lut[b & 511], bb = lut[(b + 1) & 511];
        const edge1 = this._perlinLerp(this._perlinGrad(lut[aa & 511], x, y), this._perlinGrad(lut[ba & 511], x - 1, y), u);
        const edge2 = this._perlinLerp(this._perlinGrad(lut[ab & 511], x, y - 1), this._perlinGrad(lut[bb & 511], x - 1, y - 1), u);
        return this._perlinLerp(edge1, edge2, v);
    },
    /** Multi-octave Perlin (PerlinNoise2D.Noise) */
    _perlinNoise(x, y, detail, roughness, seed) {
        this._perlinInit();
        const r = this._perlinRot;
        let total = 0, frequency = 1, amplitude = 1;
        let partial = detail;
        const octaves = Math.ceil(detail);
        for (let i = 0; i < octaves; i++) {
            const xr = x * r[0] + y * r[1];
            const yr = x * r[2] + y * r[3];
            let noise = this._perlinRaw(xr * frequency, yr * frequency, seed) * amplitude;
            if (partial < 1) noise *= partial;
            total += noise;
            amplitude *= roughness;
            if (amplitude < 0.001) break;
            frequency += frequency;
            partial -= 1.0;
            x = xr + 499;
            y = yr + 506;
        }
        return total;
    },

    _previewOneTarget(val, w, h, d) {
        const srcOrig = this.originalImageData.data;
        const ps = this._effectPreviewPxScale || 1;
        const pxU = (v) => (ps >= 1 - 1e-9 ? v : v * ps);
        const pxInt = (v) => Math.max(1, Math.round(pxU(v)));
        const pxRad = (v) => {
            const n = Number(v) || 0;
            if (n < 1) return 0;
            return Math.max(1, Math.round(pxU(n)));
        };
        const geometricOutput = (mapFn, label = "Déformation géométrique") => {
            const out = new ImageData(w, h); const od = out.data; const cx = w / 2, cy = h / 2, maxR = Math.hypot(cx, cy) || 1;
            const sy = FilterManager._startY || 0, ey = FilterManager._endY || h;
            const total = ey - sy;
            for (let y = sy; y < ey; y++) {
                if (y % 40 === 0) this.reportProgress(Math.round(((y - sy) / total) * 100), label);
                for (let x = 0; x < w; x++) {
                    const [sx, sy_] = mapFn(x, y, cx, cy, maxR); const [r, g, b, a] = this._sampleBilinear(srcOrig, w, h, sx, sy_);
                    const i = (y * w + x)*4; od[i]=r; od[i+1]=g; od[i+2]=b; od[i+3]=a;
                }
            }
            this.ctx.putImageData(out, 0, 0);
        };
        const sy = FilterManager._startY || 0, ey = FilterManager._endY || h;
        
        // --- High Performance Wasm Path ---
        // brightness avec température/teinte : le Wasm ne les gère pas → forcer le chemin JS
        const _bcExtra = this.currentEffect === 'brightness' && ((val('ef-bc-temp') || 0) !== 0 || (val('ef-bc-tint') || 0) !== 0);
        // halftone : la trame Wasm ignore variante/angle/papier et module les points par l'alpha
        // de l'image → toujours passer par illuApplyHalftone (points pleins, CMJN…).
        const _jsOnly = _bcExtra || this.currentEffect === 'halftone';
        if (typeof MasterPaintWasm !== 'undefined' && MasterPaintWasm.isLoaded && MasterPaintWasm.isEffectSupported(this.currentEffect) && !_jsOnly) {
            try {
                const res = MasterPaintWasm.applyFilter(this.currentEffect, new ImageData(new Uint8ClampedArray(srcOrig), w, h), {
                    ...vals,
                    startY: FilterManager._margin ? Math.max(0, sy - FilterManager._margin) : sy,
                    endY: FilterManager._margin ? Math.min(h, ey + FilterManager._margin) : ey,
                    ps: ps,
                    // Generic mappings for common Wasm parameters
                    radius: pxRad(val('ef-rad') || 2),
                    size: pxRad(val('ef-cry') || 12) || pxInt(val('ef-size') || 10),
                    amount: (val('ef-vig') || 50) / 100 || (val('ef-glow-a') || 40) / 100 || (val('ef-bulge') || 50) / 100 || 0.5,
                    angle: (val('ef-twist') || 0) * (Math.PI / 180),
                    shift: pxInt(val('ef-chr') || 6),
                    brightness: (val('ef-b') !== undefined ? val('ef-b') : val('ef-br')) || 0,
                    contrast: (val('ef-c') !== undefined ? val('ef-c') : val('ef-co')) || 0,
                    exposure: val('ef-exp') || 100,
                    gamma: val('ef-gamma') || 100,
                    levels: val('ef-lvl') || 4,
                    amp: pxU(val('ef-wave-a') || 12),
                    freq: val('ef-wave-f') || 14,
                    dotSize: pxU(val('ef-half-rad') || 4) * 1.5,
                    sensitivity: (val('ef-edge') || 50) / 100,
                    density: val('ef-scan-d') || 1.0,
                    opacity: (val('ef-scan-o') || 50) / 100,
                    brushSize: pxInt(val('ef-oil-brush') || 3),
                    coarseness: pxInt(val('ef-oil-coarse') || 50),
                    angle: (val('ef-angle') || 45) * (Math.PI / 180), // Also works for relief
                    minRadius: pxRad(val('ef-fglass-min') || 0),
                    maxRadius: pxRad(val('ef-fglass-max') || 3),
                    samples: pxInt(val('ef-fglass-samp') || 2),
                    tolerance: pxInt(val('ef-redeye-tol') || 70),
                    saturation: (val('ef-redeye-sat') || 90) / 100
                 });
                if (res) {
                    this.ctx.putImageData(res, 0, 0);
                    return;
                }
            } catch (err) {
                console.warn(`[filter-worker] Wasm failed for '${this.currentEffect}', falling back`, err);
            }
        }

        switch (this.currentEffect) {
            case 'brightness': {
                const br=val('ef-b')||val('ef-br')||0, co=val('ef-c')||val('ef-co')||0;
                const temp=(val('ef-bc-temp')||0)*0.5, tint=(val('ef-bc-tint')||0)*0.5;
                const img=new ImageData(new Uint8ClampedArray(srcOrig),w,h), d_=img.data, f=(259*(co+255))/(255*(259-co));
                const startIdx = sy*w*4, endIdx = ey*w*4, total = endIdx - startIdx || 1;
                for(let i=startIdx; i<endIdx; i+=4){
                    if ((i - startIdx) % 160000 === 0) this.reportProgress(Math.round(((i - startIdx) / total) * 100), "Ajustement de la luminosité");
                    let r=f*(d_[i]+br-128)+128, g=f*(d_[i+1]+br-128)+128, b=f*(d_[i+2]+br-128)+128;
                    // Température : +chaud = +rouge / -bleu ; Teinte : +magenta = -vert
                    r+=temp; b-=temp; g-=tint;
                    d_[i]=Math.max(0,Math.min(255,r)); d_[i+1]=Math.max(0,Math.min(255,g)); d_[i+2]=Math.max(0,Math.min(255,b));
                }
                this.ctx.putImageData(img,0,0); return;
            }
            case 'ral': {
                const category = val('ef-ral-category') || 'all';
                const dither = (val('ef-ral-dither') || 0) / 100;

                // Filter RAL_COLORS based on category
                let colors = typeof RAL_COLORS !== 'undefined' ? RAL_COLORS : [];
                if (category !== 'all' && colors.length > 0) {
                    let prefix = 'RAL ';
                    if (category === 'yellow') prefix += '1';
                    else if (category === 'orange') prefix += '2';
                    else if (category === 'red') prefix += '3';
                    else if (category === 'violet') prefix += '4';
                    else if (category === 'blue') prefix += '5';
                    else if (category === 'green') prefix += '6';
                    else if (category === 'grey') prefix += '7';
                    else if (category === 'brown') prefix += '8';
                    else if (category === 'white-black') prefix += '9';
                    colors = colors.filter(c => c.code.startsWith(prefix));
                }
                if (colors.length === 0 && typeof RAL_COLORS !== 'undefined') {
                    colors = RAL_COLORS;
                }

                const findNearestRal = (r, g, b) => {
                    let bestDist = Infinity;
                    let bestColor = colors[0] || { r: 0, g: 0, b: 0 };
                    for (let c = 0; c < colors.length; c++) {
                        const col = colors[c];
                        const dr = r - col.r;
                        const dg = g - col.g;
                        const db = b - col.b;
                        // Perceptually weighted Euclidean distance
                        const dist = 2 * dr * dr + 4 * dg * dg + 3 * db * db;
                        if (dist < bestDist) {
                            bestDist = dist;
                            bestColor = col;
                        }
                    }
                    return bestColor;
                };

                const img = new ImageData(new Uint8ClampedArray(srcOrig), w, h);
                const d_ = img.data;

                if (dither > 0 && colors.length > 0) {
                    const total = ey - sy;
                    for (let y = sy; y < ey; y++) {
                        if (y % 40 === 0) this.reportProgress(Math.round(((y - sy) / total) * 100), "Conversion RAL (dither)");
                        for (let x = 0; x < w; x++) {
                            const i = (y * w + x) * 4;
                            const a = d_[i + 3];
                            if (a < 128) continue;

                            const r = d_[i];
                            const g = d_[i + 1];
                            const b = d_[i + 2];

                            const nearest = findNearestRal(r, g, b);

                            const errR = (r - nearest.r) * dither;
                            const errG = (g - nearest.g) * dither;
                            const errB = (b - nearest.b) * dither;

                            d_[i] = nearest.r;
                            d_[i + 1] = nearest.g;
                            d_[i + 2] = nearest.b;

                            if (x + 1 < w) {
                                const ni = (y * w + (x + 1)) * 4;
                                d_[ni] = Math.max(0, Math.min(255, d_[ni] + errR * 7 / 16));
                                d_[ni + 1] = Math.max(0, Math.min(255, d_[ni + 1] + errG * 7 / 16));
                                d_[ni + 2] = Math.max(0, Math.min(255, d_[ni + 2] + errB * 7 / 16));
                            }
                            if (y + 1 < ey) {
                                if (x - 1 >= 0) {
                                    const ni = ((y + 1) * w + (x - 1)) * 4;
                                    d_[ni] = Math.max(0, Math.min(255, d_[ni] + errR * 3 / 16));
                                    d_[ni + 1] = Math.max(0, Math.min(255, d_[ni + 1] + errG * 3 / 16));
                                    d_[ni + 2] = Math.max(0, Math.min(255, d_[ni + 2] + errB * 3 / 16));
                                }
                                const ni_b = ((y + 1) * w + x) * 4;
                                d_[ni_b] = Math.max(0, Math.min(255, d_[ni_b] + errR * 5 / 16));
                                d_[ni_b + 1] = Math.max(0, Math.min(255, d_[ni_b + 1] + errG * 5 / 16));
                                d_[ni_b + 2] = Math.max(0, Math.min(255, d_[ni_b + 2] + errB * 5 / 16));
                                if (x + 1 < w) {
                                    const ni = ((y + 1) * w + (x + 1)) * 4;
                                    d_[ni] = Math.max(0, Math.min(255, d_[ni] + errR * 1 / 16));
                                    d_[ni + 1] = Math.max(0, Math.min(255, d_[ni + 1] + errG * 1 / 16));
                                    d_[ni + 2] = Math.max(0, Math.min(255, d_[ni + 2] + errB * 1 / 16));
                                }
                            }
                        }
                    }
                } else if (colors.length > 0) {
                    const total = ey - sy;
                    for (let y = sy; y < ey; y++) {
                        if (y % 40 === 0) this.reportProgress(Math.round(((y - sy) / total) * 100), "Conversion RAL");
                        for (let x = 0; x < w; x++) {
                            const i = (y * w + x) * 4;
                            const a = d_[i + 3];
                            if (a < 128) continue;
                            const nearest = findNearestRal(d_[i], d_[i + 1], d_[i + 2]);
                            d_[i] = nearest.r;
                            d_[i + 1] = nearest.g;
                            d_[i + 2] = nearest.b;
                        }
                    }
                }

                this.ctx.putImageData(img, 0, 0);
                return;
            }
            case 'cmjn': {
                const img = new ImageData(new Uint8ClampedArray(srcOrig), w, h);
                const d_ = img.data;

                const ic = { r: 0.0, g: 0.6, b: 0.86 };
                const im = { r: 0.88, g: 0.0, b: 0.47 };
                const iy = { r: 1.0, g: 0.94, b: 0.0 };
                const ik = { r: 0.1, g: 0.1, b: 0.1 };

                const startIdx = sy * w * 4, endIdx = ey * w * 4, total = endIdx - startIdx || 1;
                for (let i = startIdx; i < endIdx; i += 4) {
                    if ((i - startIdx) % 160000 === 0) this.reportProgress(Math.round(((i - startIdx) / total) * 100), "Conversion CMJN");
                    if (d_[i + 3] < 128) continue;
                    
                    const r = d_[i], g = d_[i + 1], b = d_[i + 2];
                    
                    const r_prime = r / 255;
                    const g_prime = g / 255;
                    const b_prime = b / 255;
                    
                    let k = 1 - Math.max(r_prime, g_prime, b_prime);
                    let c = 0, m = 0, y = 0;
                    if (k < 1) {
                        c = (1 - r_prime - k) / (1 - k);
                        m = (1 - g_prime - k) / (1 - k);
                        y = (1 - b_prime - k) / (1 - k);
                    }
                    
                    const rf = (1 - c * (1 - ic.r)) * (1 - m * (1 - im.r)) * (1 - y * (1 - iy.r)) * (1 - k * (1 - ik.r));
                    const gf = (1 - c * (1 - ic.g)) * (1 - m * (1 - im.g)) * (1 - y * (1 - iy.g)) * (1 - k * (1 - ik.g));
                    const bf = (1 - c * (1 - ic.b)) * (1 - m * (1 - im.b)) * (1 - y * (1 - iy.b)) * (1 - k * (1 - ik.b));
                    
                    d_[i] = Math.max(0, Math.min(255, Math.round(rf * 255)));
                    d_[i + 1] = Math.max(0, Math.min(255, Math.round(gf * 255)));
                    d_[i + 2] = Math.max(0, Math.min(255, Math.round(bf * 255)));
                }
                
                this.ctx.putImageData(img, 0, 0);
                return;
            }
            case 'contour': {
                const width = pxInt(val('ef-contour-width') || 3);
                const colorHex = vals['ef-contour-color'] || '#ff0000';
                const opacity = (val('ef-contour-opacity') || 100) / 100;
                const mode = val('ef-contour-mode') || 'outside';
                const corner = vals['ef-contour-corner'] || 'miter';
                const color = this._parseHexColor(colorHex);

                const img = new ImageData(new Uint8ClampedArray(srcOrig), w, h);
                const d_ = img.data;

                const total = ey - sy;
                for (let y = sy; y < ey; y++) {
                    if (y % 20 === 0) this.reportProgress(Math.round(((y - sy) / total) * 100), "Tracé des contours");
                    for (let x = 0; x < w; x++) {
                        const i = (y * w + x) * 4;
                        const currentAlpha = srcOrig[i + 3];
                        const isCurrentOpaque = currentAlpha >= 128;

                        let isBoundary = false;

                        if (mode === 'outside' && !isCurrentOpaque) {
                            for (let dy = -width; dy <= width; dy++) {
                                const ny = y + dy;
                                if (ny < 0 || ny >= h) continue;
                                for (let dx = -width; dx <= width; dx++) {
                                    if (corner === 'round' && dx * dx + dy * dy > radiusSq) continue;
                                    const nx = x + dx;
                                    if (nx < 0 || nx >= w) continue;

                                    const ni = (ny * w + nx) * 4;
                                    if (srcOrig[ni + 3] >= 128) {
                                        isBoundary = true;
                                        break;
                                    }
                                }
                                if (isBoundary) break;
                            }
                        } else if (mode === 'inside' && isCurrentOpaque) {
                            for (let dy = -width; dy <= width; dy++) {
                                const ny = y + dy;
                                if (ny < 0 || ny >= h) {
                                    isBoundary = true;
                                    break;
                                }
                                for (let dx = -width; dx <= width; dx++) {
                                    if (corner === 'round' && dx * dx + dy * dy > radiusSq) continue;
                                    const nx = x + dx;
                                    if (nx < 0 || nx >= w) {
                                        isBoundary = true;
                                        break;
                                    }

                                    const ni = (ny * w + nx) * 4;
                                    if (srcOrig[ni + 3] < 128) {
                                        isBoundary = true;
                                        break;
                                    }
                                }
                                if (isBoundary) break;
                            }
                        } else if (mode === 'both') {
                            for (let dy = -width; dy <= width; dy++) {
                                const ny = y + dy;
                                const isYOut = ny < 0 || ny >= h;
                                for (let dx = -width; dx <= width; dx++) {
                                    if (corner === 'round' && dx * dx + dy * dy > radiusSq) continue;
                                    const nx = x + dx;
                                    const isXOut = nx < 0 || nx >= w;

                                    let isNeighborOpaque = false;
                                    if (!isYOut && !isXOut) {
                                        const ni = (ny * w + nx) * 4;
                                        isNeighborOpaque = srcOrig[ni + 3] >= 128;
                                    }

                                    if (isCurrentOpaque !== isNeighborOpaque) {
                                        isBoundary = true;
                                        break;
                                    }
                                }
                                if (isBoundary) break;
                            }
                        }

                        if (isBoundary) {
                            const outAlpha = Math.round(opacity * 255);
                            if (opacity === 1) {
                                d_[i] = color.r;
                                d_[i + 1] = color.g;
                                d_[i + 2] = color.b;
                                d_[i + 3] = 255;
                            } else {
                                const a1 = opacity;
                                const a2 = (currentAlpha / 255) * (1 - opacity);
                                const aOut = a1 + a2;
                                if (aOut > 0) {
                                    d_[i] = Math.round((color.r * a1 + srcOrig[i] * a2) / aOut);
                                    d_[i + 1] = Math.round((color.g * a1 + srcOrig[i + 1] * a2) / aOut);
                                    d_[i + 2] = Math.round((color.b * a1 + srcOrig[i + 2] * a2) / aOut);
                                    d_[i + 3] = Math.round(aOut * 255);
                                }
                            }
                        }
                    }
                }

                this.ctx.putImageData(img, 0, 0);
                return;
            }
            case 'grayscale': {
                const img=new ImageData(new Uint8ClampedArray(srcOrig),w,h), d_=img.data;
                const startIdx = sy*w*4, endIdx = ey*w*4, total = endIdx - startIdx || 1;
                for(let i=startIdx; i<endIdx; i+=4){
                    if ((i - startIdx) % 160000 === 0) this.reportProgress(Math.round(((i - startIdx) / total) * 100), "Niveaux de gris");
                    const l = 0.299*d_[i]+0.587*d_[i+1]+0.114*d_[i+2];
                    d_[i]=d_[i+1]=d_[i+2]=l;
                }
                this.ctx.putImageData(img,0,0); return;
            }
            case 'invert': {
                const img=new ImageData(new Uint8ClampedArray(srcOrig),w,h), d_=img.data;
                const startIdx = sy*w*4, endIdx = ey*w*4, total = endIdx - startIdx || 1;
                for(let i=startIdx; i<endIdx; i+=4){
                    if ((i - startIdx) % 160000 === 0) this.reportProgress(Math.round(((i - startIdx) / total) * 100), "Inversion");
                    d_[i]=255-d_[i]; d_[i+1]=255-d_[i+1]; d_[i+2]=255-d_[i+2];
                }
                this.ctx.putImageData(img,0,0); return;
            }
            case 'sepia': {
                const img=new ImageData(new Uint8ClampedArray(srcOrig),w,h), d_=img.data;
                const startIdx = sy*w*4, endIdx = ey*w*4, total = endIdx - startIdx || 1;
                for(let i=startIdx; i<endIdx; i+=4){
                    if ((i - startIdx) % 160000 === 0) this.reportProgress(Math.round(((i - startIdx) / total) * 100), "Effet Sépia");
                    const r=d_[i], g=d_[i+1], b=d_[i+2];
                    d_[i]=Math.min(255, (r*0.393)+(g*0.769)+(b*0.189));
                    d_[i+1]=Math.min(255, (r*0.349)+(g*0.686)+(b*0.168));
                    d_[i+2]=Math.min(255, (r*0.272)+(g*0.534)+(b*0.131));
                }
                this.ctx.putImageData(img,0,0); return;
            }
            case 'exposure': {
                const exp=(val('ef-exp')||100)/100, gam=(val('ef-gamma')||100)/100, invG=gam>.05?1/gam:1;
                const img=new ImageData(new Uint8ClampedArray(srcOrig),w,h), d_=img.data;
                const startIdx = sy*w*4, endIdx = ey*w*4, total = endIdx - startIdx || 1;
                for(let i=startIdx; i<endIdx; i+=4){
                    if ((i - startIdx) % 160000 === 0) this.reportProgress(Math.round(((i - startIdx) / total) * 100), "Exposition & Gamma");
                    for(let c=0; c<3; c++) {
                        let v = Math.min(255, Math.max(0, d_[i+c]*exp));
                        d_[i+c]=Math.min(255, Math.max(0, Math.round(Math.pow(v/255, invG)*255)));
                    }
                }
                this.ctx.putImageData(img,0,0); return;
            }
            case 'blur':
            case 'gaussian': {
                const rad = pxRad(val('ef-rad')||2);
                const img=new ImageData(new Uint8ClampedArray(srcOrig),w,h);
                const passes = FilterManager.currentEffect === 'gaussian' ? 3 : 1;
                for (let p = 0; p < passes; p++) {
                    this._boxBlurRGBA(img.data, w, h, rad);
                    this.reportProgress(Math.round(((p + 1) / passes) * 100), "Flou");
                }
                this.ctx.putImageData(img, 0, 0); return;
            }
            case 'median': {
                // OpenPDN ReduceNoiseEffect: per-channel percentile histogram + lerp
                const srcD = new Uint8ClampedArray(srcOrig);
                const imgD = new ImageData(w, h);
                const od   = imgD.data;
                const rad  = Math.max(1, Math.min(8, parseInt(vals['ef-med-rad'] || '2', 10)));
                const strength = (parseFloat(vals['ef-med-str'] ?? '100') / 100) * 0.2;
                const total = ey - sy;
                for (let y = sy; y < ey; y++) {
                    if (y % 10 === 0) this.reportProgress(Math.round(((y - sy) / total) * 100), "Réduction du bruit");
                    for (let x = 0; x < w; x++) {
                        const hr = new Int32Array(256);
                        const hg = new Int32Array(256);
                        const hb = new Int32Array(256);
                        let area = 0;
                        for (let dy = -rad; dy <= rad; dy++) {
                            const ny = Math.max(0, Math.min(h - 1, y + dy));
                            for (let dx = -rad; dx <= rad; dx++) {
                                const nx = Math.max(0, Math.min(w - 1, x + dx));
                                const j = (ny * w + nx) * 4;
                                hr[srcD[j]]++; hg[srcD[j+1]]++; hb[srcD[j+2]]++; area++;
                            }
                        }
                        const si = (y * w + x) * 4;
                        const pR = srcD[si], pG = srcD[si+1], pB = srcD[si+2];
                        let cR = 0; for (let k = 0; k < pR; k++) cR += hr[k];
                        let cG = 0; for (let k = 0; k < pG; k++) cG += hg[k];
                        let cB = 0; for (let k = 0; k < pB; k++) cB += hb[k];
                        const nR = Math.min(255, Math.round((cR * 255) / area));
                        const nG = Math.min(255, Math.round((cG * 255) / area));
                        const nB = Math.min(255, Math.round((cB * 255) / area));
                        const luma = (0.299 * pR + 0.587 * pG + 0.114 * pB) / 255;
                        const t = Math.max(0, Math.min(1, strength * (1 - 0.75 * luma)));
                        od[si]   = Math.round(pR + (nR - pR) * t);
                        od[si+1] = Math.round(pG + (nG - pG) * t);
                        od[si+2] = Math.round(pB + (nB - pB) * t);
                        od[si+3] = srcD[si+3];
                    }
                }
                this.ctx.putImageData(imgD, 0, 0); return;
            }

            case 'oil': {
                const R = pxInt(val('ef-oil')||4);
                const img=new ImageData(new Uint8ClampedArray(srcOrig),w,h), od=img.data, src=new Uint8ClampedArray(srcOrig);
                const total = ey - sy;
                for(let y=sy; y<ey; y++){
                    if (y % 10 === 0) this.reportProgress(Math.round(((y - sy) / total) * 100), "Peinture à l'huile");
                    for(let x=0; x<w; x++){
                        const hist=new Array(512).fill(0), sR=new Array(512).fill(0), sG=new Array(512).fill(0), sB=new Array(512).fill(0);
                        for(let dy=-R; dy<=R; dy++){
                            const ny = Math.max(0, Math.min(h-1, y+dy));
                            for(let dx=-R; dx<=R; dx++){
                                const nx = Math.max(0, Math.min(w-1, x+dx));
                                const j=(ny*w+nx)*4;
                                const bi = (Math.floor(src[j]/32.1)*64) + (Math.floor(src[j+1]/32.1)*8) + Math.floor(src[j+2]/32.1);
                                hist[bi]++; sR[bi]+=src[j]; sG[bi]+=src[j+1]; sB[bi]+=src[j+2];
                            }
                        }
                        let mxC=0, mxI=0;
                        for(let k=0; k<512; k++){ if(hist[k]>mxC){mxC=hist[k]; mxI=k;} }
                        const i=(y*w+x)*4;
                        if(mxC>0){ od[i]=sR[mxI]/mxC; od[i+1]=sG[mxI]/mxC; od[i+2]=sB[mxI]/mxC; od[i+3]=src[i+3]; }
                    }
                }
                this.ctx.putImageData(img,0,0); return;
            }
            case 'bulge': geometricOutput((x,y,cx,cy,maxR)=>{ const dx=x-cx, dy=y-cy, r=Math.hypot(dx,dy), t=r/maxR; const k=(val('ef-bulge')/100)*1.5; const rS=r/(1+k*(1-t*t)); return [cx+(dx/r)*rS, cy+(dy/r)*rS]; }); return;
            case 'pinch': geometricOutput((x,y,cx,cy,maxR)=>{ const dx=x-cx, dy=y-cy, r=Math.hypot(dx,dy), t=r/maxR; const k= -(val('ef-pinch')/100)*1.5; const rS=r/(1+k*(1-t*t)); return [cx+(dx/r)*rS, cy+(dy/r)*rS]; }); return;
            case 'twist': geometricOutput((x,y,cx,cy,maxR)=>{ const dx=x-cx, dy=y-cy, r=Math.hypot(dx,dy); const a=(val('ef-twist')*Math.PI)/180 * (1-r/maxR); const th=Math.atan2(dy,dx)+a; return [cx+r*Math.cos(th), cy+r*Math.sin(th)]; }); return;
            case 'polarInvert': geometricOutput((x,y,cx,cy,maxR)=>{ const dX=x-cx, dY=y-cy, r=Math.hypot(dX,dY), th=Math.atan2(dY,dX), amt=val('ef-polar')/100; const rS=r*(1-amt)+(maxR-r)*amt; return [cx+rS*Math.cos(th), cy+rS*Math.sin(th)]; }); return;
            case 'tileReflect': geometricOutput((x,y)=>{ const T=Math.max(4, pxInt(val('ef-tile'))); const qx=Math.floor(x/T), qy=Math.floor(y/T); let tx=x-qx*T, ty=y-qy*T; const mx=tx<T/2?tx:T-1-tx, my=ty<T/2?ty:T-1-ty; return [qx*T+mx, qy*T+my]; }); return;
            case 'wave': geometricOutput((x,y)=>{ const amp=pxU(val('ef-wave-a')||12), frq=val('ef-wave-f')||14, k=(2*Math.PI)/frq; return [x+amp*Math.sin(y*k), y+amp*Math.cos(x*k)]; }); return;
            case 'chromatic': { const sh=pxInt(val('ef-chr')||6); const out=new ImageData(w,h); const total = ey - sy; for(let y=sy; y<ey; y++) { if (y % 40 === 0) this.reportProgress(Math.round(((y - sy) / total) * 100), "Aberration chromatique"); for(let x=0; x<w; x++) { const r=this._sampleBilinear(srcOrig,w,h,x-sh,y)[0], g=this._sampleBilinear(srcOrig,w,h,x,y)[1], b=this._sampleBilinear(srcOrig,w,h,x+sh,y)[2], a=this._sampleBilinear(srcOrig,w,h,x,y)[3]; const i=(y*w+x)*4; out.data[i]=r; out.data[i+1]=g; out.data[i+2]=b; out.data[i+3]=a; } } this.ctx.putImageData(out,0,0); return; }
            case 'crystallize': { const cell=pxInt(val('ef-cry')||12); const out=new ImageData(w,h), d_=out.data; for(let yy=0; yy<h; yy+=cell) { if (yy % 40 === 0) this.reportProgress(Math.round((yy / h) * 100), "Cristallisation"); for(let xx=0; xx<w; xx+=cell) { const si=(Math.min(h-1,yy+cell/2|0)*w+Math.min(w-1,xx+cell/2|0))*4, vr=srcOrig[si], vg=srcOrig[si+1], vb=srcOrig[si+2], va=srcOrig[si+3]; for(let dy=0; dy<cell && yy+dy<h; dy++) { const cy=yy+dy; if(cy<sy||cy>=ey) continue; for(let dx=0; dx<cell && xx+dx<w; dx++) { const di=(cy*w+xx+dx)*4; d_[di]=vr; d_[di+1]=vg; d_[di+2]=vb; d_[di+3]=va; } } } } this.ctx.putImageData(out,0,0); return; }
            case 'softglow': { const r=pxRad(val('ef-glow-r')||6), am=(val('ef-glow-a')||40)/100; const img=new ImageData(new Uint8ClampedArray(srcOrig),w,h), blur=new Uint8ClampedArray(srcOrig); this._boxBlurRGBA(blur,w,h,r); const startIdx = sy*w*4, endIdx = ey*w*4, total = endIdx - startIdx || 1; for(let i=startIdx; i<endIdx; i+=4){ if ((i - startIdx) % 160000 === 0) this.reportProgress(Math.round(((i - startIdx) / total) * 100), "Lueur diffuse"); img.data[i]=Math.min(255,img.data[i]+blur[i]*am); img.data[i+1]=Math.min(255,img.data[i+1]+blur[i+1]*am); img.data[i+2]=Math.min(255,img.data[i+2]+blur[i+2]*am); } this.ctx.putImageData(img,0,0); return; }
            case 'vignette': { 
                const vig=val('ef-vig')/100, cx=w/2, cy=h/2, maxR=Math.hypot(cx,cy)||1;
                const colorStr = vals['ef-vig-color'] || '#000000';
                const h_str = colorStr.replace('#', '').trim();
                const hn = parseInt(h_str, 16);
                const vc = Number.isNaN(hn) ? {r:0,g:0,b:0} : {r:(hn>>16)&255, g:(hn>>8)&255, b:hn&255};
                const blend = parseInt(vals['ef-vig-blend'] || 0, 10);
                
                const img=new ImageData(new Uint8ClampedArray(srcOrig),w,h), d_=img.data; 
                const total = ey - sy;
                for(let y=sy; y<ey; y++){ 
                    if (y % 40 === 0) this.reportProgress(Math.round(((y - sy) / total) * 100), "Vignettage");
                    for(let x=0; x<w; x++){ 
                        const dist = Math.hypot(x-cx, y-cy);
                        let normDist = dist / maxR;
                        let d = normDist * vig * 2.0;
                        let mask = 0.0;
                        if (d <= 0.2) mask = 1.0;
                        else if (d >= 0.8) mask = 0.0;
                        else {
                            let t = (d - 0.2) / (0.8 - 0.2);
                            mask = 1.0 - (t * t * (3.0 - 2.0 * t));
                        }
                        
                        const i=(y*w+x)*4; 
                        const oR = d_[i]/255, oG = d_[i+1]/255, oB = d_[i+2]/255;
                        const mR = vc.r/255, mG = vc.g/255, mB = vc.b/255;
                        
                        let fR = oR, fG = oG, fB = oB;
                        if (blend === 1) { // Multiply
                            fR = oR * mR; fG = oG * mG; fB = oB * mB;
                        } else if (blend === 2) { // Screen
                            fR = 1.0 - (1.0 - oR) * (1.0 - mR);
                            fG = 1.0 - (1.0 - oG) * (1.0 - mG);
                            fB = 1.0 - (1.0 - oB) * (1.0 - mB);
                        } else if (blend === 3) { // Overlay
                            fR = (oR < 0.5) ? (2.0 * oR * mR) : (1.0 - 2.0 * (1.0 - oR) * (1.0 - mR));
                            fG = (oG < 0.5) ? (2.0 * oG * mG) : (1.0 - 2.0 * (1.0 - oG) * (1.0 - mG));
                            fB = (oB < 0.5) ? (2.0 * oB * mB) : (1.0 - 2.0 * (1.0 - oB) * (1.0 - mB));
                        } else { // Normal
                            fR = mR; fG = mG; fB = mB;
                        }
                        
                        d_[i] = Math.max(0, Math.min(255, (oR * mask + fR * (1.0 - mask)) * 255));
                        d_[i+1] = Math.max(0, Math.min(255, (oG * mask + fG * (1.0 - mask)) * 255));
                        d_[i+2] = Math.max(0, Math.min(255, (oB * mask + fB * (1.0 - mask)) * 255));
                    } 
                } 
                this.ctx.putImageData(img,0,0); return; 
            }
            case 'sharpen': { const amt=val('ef-sharp')/100, rad=pxRad(val('ef-sharp-r')||1); const img=new ImageData(new Uint8ClampedArray(srcOrig),w,h), blur=new Uint8ClampedArray(srcOrig); this._boxBlurRGBA(blur,w,h,rad); const startIdx = sy*w*4, endIdx = ey*w*4, total = endIdx - startIdx || 1; for(let i=startIdx; i<endIdx; i+=4){ if ((i - startIdx) % 160000 === 0) this.reportProgress(Math.round(((i - startIdx) / total) * 100), "Ajustement netteté"); for(let c=0; c<3; c++) img.data[i+c]=Math.max(0,Math.min(255,srcOrig[i+c]+(srcOrig[i+c]-blur[i+c])*amt)); } this.ctx.putImageData(img,0,0); return; }
            case 'hsv': {
                const h_=val('ef-h'), s_=val('ef-s'), l_=val('ef-l'), img=new ImageData(new Uint8ClampedArray(srcOrig),w,h), d_=img.data, pm=FilterManager._hsvMixParams||{};
                const hasM = (pm.hslHue && pm.hslHue.some(v=>v!==0)) || (pm.hslSat && pm.hslSat.some(v=>v!==0)) || (pm.hslLum && pm.hslLum.some(v=>v!==0));
                const startIdx = sy*w*4, endIdx = ey*w*4, total = endIdx - startIdx || 1;
                for(let i=startIdx; i<endIdx; i+=4){
                    if ((i - startIdx) % 160000 === 0) this.reportProgress(Math.round(((i - startIdx) / total) * 100), "Teinte Saturation Lum.");
                    if(hasM){
                        let hsl=this.rgbToTrueHsl(d_[i],d_[i+1],d_[i+2]); const wgt=this.getHslWeightsFast(hsl.h);
                        const hS=pm.hslHue?(pm.hslHue[wgt.i1]*wgt.w1+pm.hslHue[wgt.i2]*wgt.w2):0, sS=pm.hslSat?(pm.hslSat[wgt.i1]*wgt.w1+pm.hslSat[wgt.i2]*wgt.w2):0, lS=pm.hslLum?(pm.hslLum[wgt.i1]*wgt.w1+pm.hslLum[wgt.i2]*wgt.w2):0;
                        hsl.h=(hsl.h+hS+h_+720)%360; hsl.s=Math.max(0,Math.min(100,hsl.s+sS+s_)); hsl.l=Math.max(0,Math.min(100,hsl.l+lS+l_));
                        const rgb=this.hslToTrueRgb(hsl.h,hsl.s,hsl.l); d_[i]=rgb.r; d_[i+1]=rgb.g; d_[i+2]=rgb.b;
                    } else {
                        let hsv=this.rgbToHsv(d_[i],d_[i+1],d_[i+2]); hsv.h=(hsv.h+h_+720)%360; hsv.s=Math.max(0,Math.min(100,hsv.s+s_)); hsv.v=Math.max(0,Math.min(100,hsv.v+l_));
                        const rgb=this.hsvToRgb(hsv.h,hsv.s,hsv.v); d_[i]=rgb.r; d_[i+1]=rgb.g; d_[i+2]=rgb.b;
                    }
                }
                this.ctx.putImageData(img,0,0); return;
            }
            case 'digitalpattern': {
                const str = val('ef-grain') / 100, cell = Math.max(2, pxInt(val('ef-grain-fine')));
                const img = new ImageData(new Uint8ClampedArray(srcOrig), w, h), d_ = img.data;
                const total = ey - sy;
                for (let y = sy; y < ey; y++) {
                    if (y % 40 === 0) this.reportProgress(Math.round(((y - sy) / total) * 100), "Grain numérique");
                    for (let x = 0; x < w; x++) {
                    const n = this._grainNoise((x / cell) | 0, (y / cell) | 0) * str * 64, i = (y * w + x) * 4;
                    for (let c = 0; c < 3; c++) d_[i + c] = Math.min(255, Math.max(0, d_[i + c] + n));
                } }
                this.ctx.putImageData(img, 0, 0); return;
            }
            case 'halftone': {
                const opts = illuHalftoneOptsFromVals(vals, ps);
                const label = opts.mode === 'cmyk' ? 'Trame CMJN' : 'Demi-teintes';
                const res = illuApplyHalftone(srcOrig, w, h, opts, sy, ey, (p) => this.reportProgress(p, label));
                this.ctx.putImageData(new ImageData(res, w, h), 0, 0);
                return;
            }
            case 'duotone': {
                const c1 = this._parseHexColor(vals['ef-duo-c1'] || '#1a0533'), c2 = this._parseHexColor(vals['ef-duo-c2'] || '#fff5e0'), piv = val('ef-duo-mid') || 128;
                const img = new ImageData(new Uint8ClampedArray(srcOrig), w, h), d_ = img.data;
                const startIdx = sy * w * 4, endIdx = ey * w * 4, total = endIdx - startIdx || 1;
                for (let i = startIdx; i < endIdx; i += 4) {
                    if ((i - startIdx) % 160000 === 0) this.reportProgress(Math.round(((i - startIdx) / total) * 100), "Bicontraste");
                    const l = (0.299 * d_[i] + 0.587 * d_[i + 1] + 0.114 * d_[i + 2]);
                    const t = l < piv ? (l / piv) * 0.5 : 0.5 + ((l - piv) / (256 - piv)) * 0.5;
                    d_[i] = c1.r + t * (c2.r - c1.r); d_[i + 1] = c1.g + t * (c2.g - c1.g); d_[i + 2] = c1.b + t * (c2.b - c1.b);
                }
                this.ctx.putImageData(img, 0, 0); return;
            }
            case 'edges': {
                const sens = (val('ef-edge')||50)/100, img = new ImageData(w, h), d_ = img.data;
                const gray = new Float32Array(w * h); for (let j = 0; j < w * h; j++) gray[j] = 0.299 * srcOrig[j * 4] + 0.587 * srcOrig[j * 4 + 1] + 0.114 * srcOrig[j * 4 + 2];
                const g = (xx, yy) => (xx >= 0 && xx < w && yy >= 0 && yy < h) ? gray[yy * w + xx] : 0;
                const total = ey - sy;
                for (let y = sy; y < ey; y++) {
                    if (y % 40 === 0) this.reportProgress(Math.round(((y - sy) / total) * 100), "Détection des contours");
                    for (let x = 0; x < w; x++) {
                    const h_ = g(x - 1, y - 1) + 2 * g(x - 1, y) + g(x - 1, y + 1) - (g(x + 1, y - 1) + 2 * g(x + 1, y) + g(x + 1, y + 1));
                    const v_ = g(x - 1, y - 1) + 2 * g(x, y - 1) + g(x + 1, y - 1) - (g(x - 1, y + 1) + 2 * g(x, y + 1) + g(x + 1, y + 1));
                    const edge = Math.sqrt(h_ * h_ + v_ * v_), i = (y * w + x) * 4;
                    d_[i] = d_[i + 1] = d_[i + 2] = Math.min(255, edge * sens * 4); d_[i+3]=srcOrig[i+3];
                } }
                this.ctx.putImageData(img, 0, 0); return;
            }
            case 'chroma': {
                if(typeof ChromaKeyer==='undefined') return;
                const kr=Math.max(0,Math.min(255,val('ef-ch-r'))), kg=Math.max(0,Math.min(255,val('ef-ch-g'))), kb=Math.max(0,Math.min(255,val('ef-ch-b')));
                const p={ tolerance:val('ef-ch-tol')||30, drift:val('ef-ch-drift'), feather:val('ef-ch-feather'), clipBlack:val('ef-ch-black'), clipWhite:vals['ef-ch-white']!==undefined?val('ef-ch-white'):100, gamma:val('ef-ch-gamma')||1.0, spill:val('ef-ch-spill') };
                const img=new ImageData(new Uint8ClampedArray(srcOrig),w,h), d_=img.data;
                const startIdx = sy*w*4, endIdx = ey*w*4, total = endIdx - startIdx || 1;
                for(let i=startIdx; i<endIdx; i+=4){
                    if ((i - startIdx) % 160000 === 0) this.reportProgress(Math.round(((i - startIdx) / total) * 100), "Incrustation couleur");
                    const k_=ChromaKeyer.computeMatte(d_[i],d_[i+1],d_[i+2],kr,kg,kb,p); d_[i+3]=Math.round(d_[i+3]*k_);
                    if(p.spill>0 && d_[i+3]>0){ const rr_=ChromaKeyer.applyDespill(d_[i],d_[i+1],d_[i+2],kr,kg,kb,p.spill); d_[i]=rr_[0]; d_[i+1]=rr_[1]; d_[i+2]=rr_[2]; }
                }
                this.ctx.putImageData(img,0,0); return;
            }
            case 'vhs': {
                const applyVhs = typeof illuApplyVhsToRgba === 'function' ? illuApplyVhsToRgba : null;
                if (!applyVhs) {
                    this.ctx.putImageData(new ImageData(new Uint8ClampedArray(srcOrig), w, h), 0, 0);
                    return;
                }
                const params =
                    typeof illuMergeVhsParams === 'function' ? illuMergeVhsParams(vals) : Object.assign({}, vals);
                /*
                 * Aperçu réduit : les réglages exprimés en pixels doivent suivre l'échelle,
                 * sinon un décalage chroma de 13 px paraît deux fois plus fort sur un aperçu
                 * demi-résolution que sur le rendu final.
                 *
                 * Trois catégories. Les autres réglages (chroma_bleed en dB, saturations,
                 * fréquences, band_patina en fraction) ne sont pas des longueurs : les
                 * mettre à l'échelle changerait le rendu, et ramener pixel_size sous 1 px
                 * fait tourner le cœur de l'effet à vide.
                 *
                 * luma_smear et tear_max_height sont volontairement absents : ce sont des
                 * pourcentages (intensité du bavement, hauteur de zone de déchirure en %
                 * de l'image), pas des distances en pixels.
                 */
                if (ps < 1 - 1e-9) {
                    /* Longueurs continues : une valeur fractionnaire ne gêne pas. */
                    const VHS_LEN_KEYS = [
                        'crop_padding', 'crop_feather', 'shift_y', 'shift_r', 'shift_g', 'shift_b',
                        'head_switch_pull', 'head_switch_rows'
                    ];
                    for (let i = 0; i < VHS_LEN_KEYS.length; i++) {
                        const k = VHS_LEN_KEYS[i];
                        const v = params[k];
                        if (typeof v === 'number' && v !== 0) params[k] = v * ps;
                    }
                    /*
                     * Rayons servant d'index de boucle : ils doivent rester entiers. Un
                     * chroma_blur de 25 px ramené à 9,375 indexait rowI/rowQ en décimal —
                     * `undefined`, puis NaN, et un aperçu entièrement noir.
                     */
                    const VHS_RADIUS_KEYS = ['chroma_blur'];
                    for (let i = 0; i < VHS_RADIUS_KEYS.length; i++) {
                        const k = VHS_RADIUS_KEYS[i];
                        const v = params[k];
                        if (typeof v === 'number' && v > 0) params[k] = Math.max(0, Math.round(v * ps));
                    }
                    /* Épaisseurs en pixels entiers : jamais moins d'un pixel. */
                    const VHS_THICK_KEYS = ['pixel_size', 'tear_thickness', 'dropout_thickness'];
                    for (let i = 0; i < VHS_THICK_KEYS.length; i++) {
                        const k = VHS_THICK_KEYS[i];
                        const v = params[k];
                        if (typeof v === 'number' && v > 0) params[k] = Math.max(1, Math.round(v * ps));
                    }
                }
                const out = applyVhs(new Uint8ClampedArray(srcOrig), w, h, params, 0);
                if (out) {
                    this.ctx.putImageData(new ImageData(out, w, h), 0, 0);
                } else {
                    this.ctx.putImageData(new ImageData(new Uint8ClampedArray(srcOrig), w, h), 0, 0);
                }
                return;
            }
            case 'addnoise': {
                const int = val('ef-int')||20, img=new ImageData(new Uint8ClampedArray(srcOrig),w,h), d_=img.data;
                for(let i=sy*w*4; i<ey*w*4; i+=4){
                    const noise = (Math.random()-0.5)*int;
                    for(let c=0; c<3; c++) d_[i+c]=Math.max(0,Math.min(255, d_[i+c]+noise));
                }
                this.ctx.putImageData(img,0,0); return;
            }
            case 'argenticgrain': {
                const str = (val('ef-grain')||40)/100, img=new ImageData(new Uint8ClampedArray(srcOrig),w,h), d_=img.data;
                for(let i=sy*w*4; i<ey*w*4; i+=4){
                    const noise = (Math.random()-0.5)*str*128;
                    for(let c=0; c<3; c++) d_[i+c]=Math.max(0,Math.min(255, d_[i+c]+noise));
                }
                this.ctx.putImageData(img,0,0); return;
            }
            case 'pixelate': {
                const size = pxInt(val('ef-size')||10);
                const out = new ImageData(w,h), d_=out.data;
                for(let yy=0; yy<h; yy+=size){
                    for(let xx=0; xx<w; xx+=size){
                        const si=(yy*w+xx)*4, vr=srcOrig[si], vg=srcOrig[si+1], vb=srcOrig[si+2], va=srcOrig[si+3];
                        for(let dy=0; dy<size && yy+dy<h; dy++){
                            const cy=yy+dy; if(cy<sy || cy>=ey) continue;
                            for(let dx=0; dx<size && xx+dx<w; dx++){
                                const di=(cy*w+xx+dx)*4; d_[di]=vr; d_[di+1]=vg; d_[di+2]=vb; d_[di+3]=va;
                            }
                        }
                    }
                }
                this.ctx.putImageData(out,0,0); return;
            }
            case 'posterize': {
                const levels = Math.max(2, val('ef-lvl')||4), step = 255/(levels-1);
                const img = new ImageData(new Uint8ClampedArray(srcOrig),w,h), d_=img.data;
                for(let i=sy*w*4; i<ey*w*4; i+=4){
                    for(let c=0; c<3; c++) d_[i+c]=Math.round(d_[i+c]/step)*step;
                }
                this.ctx.putImageData(img,0,0); return;
            }
            case 'projection3d': {
                const rx=val('ef-3d-rx'), ry=val('ef-3d-ry'), focal=Math.max(80, Math.min(800, Math.round(pxU(val('ef-3d-f'))))), zoom=(val('ef-3d-z')||100)/100;
                const tl=val('ef-3d-tl'), tr=val('ef-3d-tr'), br=val('ef-3d-br'), bl=val('ef-3d-bl');
                let dstQuad=this._quadCorners3D(w, h, rx, ry, focal, zoom); dstQuad=this._pullCorners(dstQuad, w, h, tl, tr, br, bl);
                const srcQuad=[[0,0],[w,0],[w,h],[0,h]], H=this._solveHomography8(srcQuad, dstQuad); if(!H) return;
                const Hinv=this._invert3x3(H); if(!Hinv) return;
                const out=new ImageData(w,h), od=out.data;
                for(let y=sy; y<ey; y++) { for(let x=0; x<w; x++) {
                    const q0=Hinv[0]*x+Hinv[1]*y+Hinv[2], q1=Hinv[3]*x+Hinv[4]*y+Hinv[5], q2=Hinv[6]*x+Hinv[7]*y+Hinv[8], i=(y*w+x)*4;
                    if(Math.abs(q2)<1e-9) { od[i]=od[i+1]=od[i+2]=od[i+3]=0; continue; }
                    const sx=q0/q2, sy_=q1/q2;
                    if(sx<-0.5 || sy_<-0.5 || sx>=w-0.5 || sy_>=h-0.5) { od[i]=od[i+1]=od[i+2]=od[i+3]=0; }
                    else { const [r,g,b,a]=this._sampleBilinear(srcOrig,w,h,sx,sy_); od[i]=r; od[i+1]=g; od[i+2]=b; od[i+3]=a; }
                } }
                this.ctx.putImageData(out, 0, 0); return;
            }
            case 'sketch': {
                const img=new ImageData(new Uint8ClampedArray(srcOrig),w,h), d_=img.data;
                for(let i=sy*w*4; i<ey*w*4; i+=4){
                    const avg=(d_[i]+d_[i+1]+d_[i+2])/3; let v=255-avg;
                    v=Math.max(0, Math.min(255, (v-128)*5+128)); d_[i]=d_[i+1]=d_[i+2]=v;
                }
                this.ctx.putImageData(img, 0, 0); return;
            }
            case 'colorbal': {
                const dr=val('ef-cb-r'), dg=val('ef-cb-g'), db=val('ef-cb-b'), cb=FilterManager._cbParams||{};
                const hasP=arr=>arr&&arr.length>=2, core=self.IlluImageAdjustCore;
                const lutM=hasP(cb.curveMaster)&&core?core.createCurveLUT(cb.curveMaster):null;
                const lutR=hasP(cb.curveR)&&core?core.createCurveLUT(cb.curveR):null;
                const lutG=hasP(cb.curveG)&&core?core.createCurveLUT(cb.curveG):null;
                const lutB=hasP(cb.curveB)&&core?core.createCurveLUT(cb.curveB):null;
                const img=new ImageData(new Uint8ClampedArray(srcOrig),w,h), d_=img.data;
                for(let i=sy*w*4; i<ey*w*4; i+=4){
                    let r=Math.min(255,Math.max(0,d_[i]+dr)), g=Math.min(255,Math.max(0,d_[i+1]+dg)), b=Math.min(255,Math.max(0,d_[i+2]+db));
                    if(lutM){ r=lutM[r]; g=lutM[g]; b=lutM[b]; }
                    if(lutR)r=lutR[r]; if(lutG)g=lutG[g]; if(lutB)b=lutB[b];
                    d_[i]=r; d_[i+1]=g; d_[i+2]=b;
                }
                this.ctx.putImageData(img, 0, 0); return;
            }
            case 'cameraRaw': {
                const core = typeof self !== 'undefined' && self.IlluImageAdjustCore ? self.IlluImageAdjustCore : null;
                if(core) { const res = core.applyCameraRawBuffer(new Uint8ClampedArray(srcOrig), w, h, vals); this.ctx.putImageData(new ImageData(res, w, h), 0, 0); }
                else this.ctx.putImageData(new ImageData(new Uint8ClampedArray(srcOrig),w,h), 0,0);
                return;
            }
            case 'motionblur': {
                const pfx = typeof PdnEffects !== 'undefined' ? PdnEffects : (typeof self !== 'undefined' ? self.PdnEffects : null);
                if (pfx && typeof pfx.motionBlur === 'function') {
                    const angle = parseFloat(vals['ef-mblur-angle'] || '25');
                    const dist = Math.max(1, Math.round(pxU(parseInt(vals['ef-mblur-dist'] || '10', 10))));
                    const centered = vals['ef-mblur-center'] === '1' || vals['ef-mblur-center'] === true;
                    const img = new ImageData(new Uint8ClampedArray(srcOrig), w, h);
                    const out = pfx.motionBlur(img, angle, dist, centered);
                    this.ctx.putImageData(out, 0, 0);
                } else {
                    this.ctx.putImageData(new ImageData(new Uint8ClampedArray(srcOrig), w, h), 0, 0);
                }
                return;
            }
            case 'surfaceblur': {
                const pfx = typeof PdnEffects !== 'undefined' ? PdnEffects : (typeof self !== 'undefined' ? self.PdnEffects : null);
                if (pfx && typeof pfx.surfaceBlur === 'function') {
                    const rad = pxRad(parseInt(vals['ef-sblur-r'] || '6', 10));
                    const th = parseInt(vals['ef-sblur-t'] || '15', 10);
                    const img = new ImageData(new Uint8ClampedArray(srcOrig), w, h);
                    const out = pfx.surfaceBlur(img, rad, th);
                    this.ctx.putImageData(out, 0, 0);
                } else {
                    const rad = pxRad(parseInt(vals['ef-sblur-r'] || '6', 10)) || 1;
                    const img = new ImageData(new Uint8ClampedArray(srcOrig), w, h);
                    this._boxBlurRGBA(img.data, w, h, rad);
                    this.ctx.putImageData(img, 0, 0);
                }
                return;
            }
            case 'mirrorquad': {
                geometricOutput((x, y) => {
                    const qx = x < w / 2 ? x : w - 1 - x;
                    const qy = y < h / 2 ? y : h - 1 - y;
                    return [qx, qy];
                });
                return;
            }
            case 'radialblur': {
                const fn = typeof illuRadialBlurRGBA === 'function' ? illuRadialBlurRGBA : null;
                if (!fn) {
                    this.ctx.putImageData(new ImageData(new Uint8ClampedArray(srcOrig), w, h), 0, 0);
                    return;
                }
                const out = fn(srcOrig, w, h, {
                    angle:       Math.max(0, parseFloat(vals['ef-rblur-angle']   ?? 2)),
                    quality:     Math.max(1, Math.min(5, parseInt(vals['ef-rblur-quality'] ?? 2, 10))),
                    innerRadius: Math.max(0, Math.min(1, parseFloat(vals['ef-rblur-inner'] ?? 0) / 100)),
                    offsetX:     (parseFloat(vals['ef-rblur-ox'] ?? 0)) / 100,
                    offsetY:     (parseFloat(vals['ef-rblur-oy'] ?? 0)) / 100,
                    startY:      sy,
                    endY:        ey,
                    onProgress:  (percent) => this.reportProgress(percent, "Flou radial")
                });
                this.ctx.putImageData(new ImageData(out, w, h), 0, 0);
                return;
            }
            case 'zoomblur': {
                const fn = typeof illuZoomBlurRGBA === 'function' ? illuZoomBlurRGBA : null;
                if (!fn) {
                    this.ctx.putImageData(new ImageData(new Uint8ClampedArray(srcOrig), w, h), 0, 0);
                    return;
                }
                const out = fn(srcOrig, w, h, {
                    amount:      Math.max(0, Math.min(100, parseFloat(vals['ef-zblur-amount'] ?? 10))),
                    innerRadius: Math.max(0, Math.min(1, parseFloat(vals['ef-zblur-inner'] ?? 0) / 100)),
                    offsetX:     (parseFloat(vals['ef-zblur-ox'] ?? 0)) / 100,
                    offsetY:     (parseFloat(vals['ef-zblur-oy'] ?? 0)) / 100,
                    startY:      sy,
                    endY:        ey,
                    onProgress:  (percent) => this.reportProgress(percent, "Flou de zoom")
                });
                this.ctx.putImageData(new ImageData(out, w, h), 0, 0);
                return;
            }
            case 'cabossage': {
                const scaleUi = parseFloat(vals['ef-cab-scale']) || 25;
                const refrUi = parseFloat(vals['ef-cab-refr']) || 50;
                const roughUi = parseFloat(vals['ef-cab-rough']) || 10;
                const tensionUi = parseFloat(vals['ef-cab-tension']) || 10;
                const qUi = parseFloat(vals['ef-cab-q']) || 2;
                const seed = (vals._cabossageSeed != null ? vals._cabossageSeed : this._cabossageSeed) >>> 0;
                this.reportProgress(10, "Génération de la carte de hauteur");
                const H = this._buildCabossageHeightField(w, h, scaleUi, roughUi, tensionUi, qUi, seed);
                const str = (refrUi / 100) * Math.min(w, h) * 0.1;
                const out = new ImageData(w, h);
                const od = out.data;
                const total = ey - sy;
                for (let y = sy; y < ey; y++) {
                    if (y % 20 === 0) this.reportProgress(Math.min(99, Math.round(15 + ((y - sy) / total) * 84)), "Déformation des pixels");
                    for (let x = 0; x < w; x++) {
                        const i = y * w + x;
                        let hx = 0;
                        let hy = 0;
                        if (x > 0 && x < w - 1) hx = (H[i + 1] - H[i - 1]) * 0.5;
                        else if (x > 0) hx = H[i] - H[i - 1];
                        else if (x < w - 1) hx = H[i + 1] - H[i];
                        if (y > 0 && y < h - 1) hy = (H[i + w] - H[i - w]) * 0.5;
                        else if (y > 0) hy = H[i] - H[i - w];
                        else if (y < h - 1) hy = H[i + w] - H[i];
 
                        const di = i * 4;
                        const sx = x + hx * str;
                        const sy_ = y + hy * str;
                        const [r, g, b, a] = this._sampleBilinear(srcOrig, w, h, sx, sy_);
                        od[di] = r;
                        od[di + 1] = g;
                        od[di + 2] = b;
                        od[di + 3] = a;
                    }
                }
                this.ctx.putImageData(out, 0, 0);
                return;
            }
            case 'clouds': {
                // OpenPDN CloudsEffect — rendu procédural Perlin, primaire→secondaire
                const hex2 = (s) => { const m = /^#?([0-9a-f]{6})$/i.exec(String(s || '')); const n = m ? parseInt(m[1], 16) : 0; return [(n >> 16) & 255, (n >> 8) & 255, n & 255]; };
                const from = hex2(vals['ef-clouds-from'] || '#000000');
                const to = hex2(vals['ef-clouds-to'] || '#ffffff');
                const scale = Math.max(1, pxU(val('ef-clouds-scale') || 250));
                const power = (val('ef-clouds-power') || 50) / 100;
                const seed = (val('ef-clouds-seed') || 0) & 255;
                this._perlinInit();
                const out = new ImageData(w, h), od = out.data; const total = ey - sy || 1;
                for (let y = sy; y < ey; y++) {
                    if (y % 16 === 0) this.reportProgress(Math.round(((y - sy) / total) * 100), "Nuages");
                    const dy = 2 * y - h;
                    for (let x = 0; x < w; x++) {
                        const dx = 2 * x - w;
                        let v = 0, mult = 1, div = scale;
                        for (let i = 0; i < 12 && mult > 0.03 && div > 0; i++) {
                            let dxr = 65536 + dx / div, dyr = 65536 + dy / div;
                            const dxd = dxr | 0, dyd = dyr | 0;
                            dxr -= dxd; dyr -= dyd;
                            const noise = this._perlinRaw2((dxd & 255), (dyd & 255), dxr, dyr, (seed ^ i) & 255);
                            v += noise * mult; div = Math.floor(div / 2); mult *= power;
                        }
                        let t = (v + 1) / 2; t = t < 0 ? 0 : t > 1 ? 1 : t;
                        const i4 = (y * w + x) * 4;
                        od[i4] = from[0] + (to[0] - from[0]) * t;
                        od[i4 + 1] = from[1] + (to[1] - from[1]) * t;
                        od[i4 + 2] = from[2] + (to[2] - from[2]) * t;
                        od[i4 + 3] = 255;
                    }
                }
                this.ctx.putImageData(out, 0, 0); return;
            }
            case 'mandelbrot':
            case 'julia': {
                // OpenPDN Mandelbrot/Julia Fractal
                const isJulia = this.currentEffect === 'julia';
                const factor = Math.max(1, val(isJulia ? 'ef-jl-factor' : 'ef-mb-factor') || (isJulia ? 4 : 1));
                const angle = val(isJulia ? 'ef-jl-angle' : 'ef-mb-angle') || 0;
                const quality = Math.max(1, Math.min(5, val(isJulia ? 'ef-jl-quality' : 'ef-mb-quality') || 2));
                const invert = !isJulia && (vals['ef-mb-invert'] === '1' || vals['ef-mb-invert'] === true);
                const angleTheta = (angle * 2 * Math.PI) / 360;
                const count = quality * quality + 1, invCount = 1 / count, invQuality = 1 / quality;
                const invH = 1 / h, aspect = h / w;
                const clampB = (v) => v < 0 ? 0 : v > 255 ? 255 : v | 0;
                let zoom, invZoom, xOffset, yOffset;
                const maxM = 100000, invLogMax = 1 / Math.log(maxM), log2_10000 = Math.log(10000);
                if (isJulia) { zoom = Math.max(0.1, val('ef-jl-zoom') || 4); invZoom = 1 / zoom; }
                else { zoom = 1 + 20 * (val('ef-mb-zoom') || 10); invZoom = 1 / zoom; xOffset = -0.7; yOffset = -0.29; }
                const out = new ImageData(w, h), od = out.data; const total = ey - sy || 1;
                const jr = 0.3125, ji = 0.03;
                for (let y = sy; y < ey; y++) {
                    if (y % 8 === 0) this.reportProgress(Math.round(((y - sy) / total) * 100), isJulia ? "Fractale Julia" : "Fractale Mandelbrot");
                    for (let x = 0; x < w; x++) {
                        let r = 0, g = 0, b = 0, a = 0;
                        for (let i = 0; i < count; i++) {
                            const u = (2 * x - w + i * invCount) * invH;
                            const v = (2 * y - h + ((i * invQuality) % 1)) * invH;
                            const radius = Math.sqrt(u * u + v * v), theta = Math.atan2(v, u) + angleTheta;
                            const uP = radius * Math.cos(theta), vP = radius * Math.sin(theta);
                            let c;
                            if (isJulia) {
                                let jx = (uP - vP * aspect) * invZoom, jy = (vP + uP * aspect) * invZoom, cc = 0;
                                while (cc < 256 && jx * jx + jy * jy < 10000) { const t = jx; jx = jx * jx - jy * jy + jr; jy = 2 * t * jy + ji; ++cc; }
                                cc -= 2 - 2 * log2_10000 / Math.log(jx * jx + jy * jy);
                                c = factor * cc;
                                b += clampB(c - 768); g += clampB(c - 512); r += clampB(c - 256); a += clampB(c);
                            } else {
                                const mr = uP * invZoom + xOffset, mi = vP * invZoom + yOffset;
                                let cc = 0, mx = 0, my = 0;
                                while (cc * factor < 1024 && mx * mx + my * my < maxM) { const t = mx; mx = mx * mx - my * my + mr; my = 2 * t * my + mi; ++cc; }
                                const m = cc - Math.log(my * my + mx * mx) * invLogMax;
                                c = 64 + factor * m;
                                r += clampB(c - 768); g += clampB(c - 512); b += clampB(c - 256); a += clampB(c);
                            }
                        }
                        const i4 = (y * w + x) * 4;
                        let R = clampB(r / count), G = clampB(g / count), B = clampB(b / count);
                        if (invert) { R = 255 - R; G = 255 - G; B = 255 - B; }
                        od[i4] = R; od[i4 + 1] = G; od[i4 + 2] = B; od[i4 + 3] = clampB(a / count);
                    }
                }
                this.ctx.putImageData(out, 0, 0); return;
            }
            case 'pencilsketch': {
                // OpenPDN PencilSketchEffect — grey ÷ blur(grey) (color dodge)
                const tip = pxRad(val('ef-pencil-tip') || 2) || 1;
                const range = val('ef-pencil-range') || 0;
                const lum = (i) => (srcOrig[i] * 77 + srcOrig[i + 1] * 151 + srcOrig[i + 2] * 28) >> 8;
                const grey = new Uint8ClampedArray(w * h * 4);
                for (let p = 0, q = 0; p < w * h; p++, q += 4) { const g = lum(q); grey[q] = grey[q + 1] = grey[q + 2] = g; grey[q + 3] = 255; }
                const blur = grey.slice(); this._boxBlurRGBA(blur, w, h, tip);
                const cf = (259 * (-range + 255)) / (255 * (259 - (-range)));
                const img = new ImageData(new Uint8ClampedArray(srcOrig), w, h), d_ = img.data;
                const total = ey - sy || 1;
                for (let y = sy; y < ey; y++) {
                    if (y % 24 === 0) this.reportProgress(Math.round(((y - sy) / total) * 100), "Croquis crayon");
                    for (let x = 0; x < w; x++) {
                        const i = (y * w + x) * 4;
                        const g = (srcOrig[i] * 77 + srcOrig[i + 1] * 151 + srcOrig[i + 2] * 28) >> 8;
                        let bg = cf * (blur[i] - 127) + 127 + range; bg = bg < 0 ? 0 : bg > 255 ? 255 : bg;
                        const res = bg < 1 ? 255 : Math.min(255, (g * 255) / bg);
                        d_[i] = d_[i + 1] = d_[i + 2] = res;
                    }
                }
                this.ctx.putImageData(img, 0, 0); return;
            }
            case 'softenportrait': {
                // OpenPDN SoftenPortraitEffect
                const softness = val('ef-soft-softness'); const sft = (softness === 0 ? 0 : softness || 5);
                const lighting = val('ef-soft-lighting') || 0, warmth = val('ef-soft-warmth') || 10;
                const blurRad = pxRad(sft * 3);
                const blur = new Uint8ClampedArray(srcOrig); if (blurRad > 0) this._boxBlurRGBA(blur, w, h, blurRad);
                const cf = (259 * (-(lighting / 2) + 255)) / (255 * (259 - (-(lighting / 2))));
                const redAdj = 1 + warmth / 100, blueAdj = 1 - warmth / 100;
                const ov = (base, top) => base < 128 ? (2 * base * top) / 255 : 255 - (2 * (255 - base) * (255 - top)) / 255;
                const img = new ImageData(new Uint8ClampedArray(srcOrig), w, h), d_ = img.data;
                const total = ey - sy || 1;
                for (let y = sy; y < ey; y++) {
                    if (y % 24 === 0) this.reportProgress(Math.round(((y - sy) / total) * 100), "Portrait adouci");
                    for (let x = 0; x < w; x++) {
                        const i = (y * w + x) * 4;
                        const g = (srcOrig[i] * 77 + srcOrig[i + 1] * 151 + srcOrig[i + 2] * 28) >> 8;
                        const gr = Math.max(0, Math.min(255, g * redAdj)), gb = Math.max(0, Math.min(255, g * blueAdj));
                        const bc = (c) => { let v = cf * (c - 127) + 127 + lighting; return v < 0 ? 0 : v > 255 ? 255 : v; };
                        d_[i] = ov(bc(blur[i]), gr);
                        d_[i + 1] = ov(bc(blur[i + 1]), g);
                        d_[i + 2] = ov(bc(blur[i + 2]), gb);
                    }
                }
                this.ctx.putImageData(img, 0, 0); return;
            }
            case 'reducenoise': {
                // OpenPDN ReduceNoiseEffect — percentile local (histogramme disque)
                const radius = Math.min(20, pxRad(val('ef-rn-radius') || 10) || 1);
                const strength = -0.2 * ((val('ef-rn-strength') || 40) / 100);
                const img = new ImageData(new Uint8ClampedArray(srcOrig), w, h), d_ = img.data;
                const hr = new Int32Array(256), hg = new Int32Array(256), hb = new Int32Array(256);
                const total = ey - sy || 1;
                for (let y = sy; y < ey; y++) {
                    if (y % 4 === 0) this.reportProgress(Math.round(((y - sy) / total) * 100), "Réduction du bruit");
                    for (let x = 0; x < w; x++) {
                        hr.fill(0); hg.fill(0); hb.fill(0); let area = 0;
                        for (let dy = -radius; dy <= radius; dy++) {
                            const yy = y + dy; if (yy < 0 || yy >= h) continue;
                            const span = (radius * radius - dy * dy); if (span < 0) continue;
                            const rx = Math.floor(Math.sqrt(span));
                            for (let dx = -rx; dx <= rx; dx++) {
                                const xx = x + dx; if (xx < 0 || xx >= w) continue;
                                const j = (yy * w + xx) * 4; hr[srcOrig[j]]++; hg[srcOrig[j + 1]]++; hb[srcOrig[j + 2]]++; area++;
                            }
                        }
                        if (area < 1) continue;
                        const i = (y * w + x) * 4;
                        const cr = srcOrig[i], cg = srcOrig[i + 1], cb = srcOrig[i + 2];
                        let rc = 0, gc = 0, bc = 0;
                        for (let k = 0; k < cr; k++) rc += hr[k];
                        for (let k = 0; k < cg; k++) gc += hg[k];
                        for (let k = 0; k < cb; k++) bc += hb[k];
                        const nr = (rc * 255) / area, ng = (gc * 255) / area, nb = (bc * 255) / area;
                        const intensity = ((cr * 77 + cg * 151 + cb * 28) >> 8) / 255;
                        const t = strength * (1 - 0.75 * intensity);
                        d_[i] = Math.max(0, Math.min(255, cr + (nr - cr) * t));
                        d_[i + 1] = Math.max(0, Math.min(255, cg + (ng - cg) * t));
                        d_[i + 2] = Math.max(0, Math.min(255, cb + (nb - cb) * t));
                    }
                }
                this.ctx.putImageData(img, 0, 0); return;
            }
            case 'dents': {
                // OpenPDN DentsEffect — distorsion par bruit de Perlin
                const scale = val('ef-dent-scale') || 25, refraction = val('ef-dent-refr') || 50;
                const roughUi = val('ef-dent-rough') || 10, tension = val('ef-dent-tension') || 10;
                const seed = (val('ef-dent-seed') || 0) & 255;
                const defaultRadius = Math.sqrt(w * w + h * h) / 2;
                const scaleR = (400 / defaultRadius) / Math.max(1, scale);
                const refractionScale = (refraction / 100) / scaleR;
                const theta = Math.PI * 2 * tension / 10;
                const roughness = roughUi / 100;
                let detail = 1 + roughUi / 10;
                const maxDetail = Math.floor(Math.log(scaleR) / Math.log(0.5));
                if (detail > maxDetail && maxDetail >= 1) detail = maxDetail;
                this._perlinInit();
                geometricOutput((x, y, cx, cy) => {
                    const rx = x - cx, ry = y - cy;
                    const bumpAngle = theta * this._perlinNoise(rx * scaleR, ry * scaleR, detail, roughness, seed);
                    return [cx + rx + refractionScale * Math.sin(-bumpAngle), cy + ry + refractionScale * Math.cos(bumpAngle)];
                }, "Bosselage");
                return;
            }
            case 'unfocus': {
                // Flou d'objectif / BOKEH : vrai disque circulaire + floraison des hautes lumières.
                // La moyenne se fait en espace « lumière » (v^gamma) : les points clairs dominent et
                // se répandent en disques lumineux — la signature du bokeh, absente d'un flou moyen.
                const radius = pxRad(val('ef-unfocus-r') || 8) || 1;
                const hl = Math.max(0, Math.min(1, (val('ef-unfocus-hl') != null ? val('ef-unfocus-hl') : 55) / 100));
                const gamma = 1 + hl * 3;       // 1 = flou plat, 4 = fort bloom
                const invG = 1 / gamma;
                const N = w * h;
                // Prémultiplié alpha, élevé en espace lumière
                const pr = new Float32Array(N), pg = new Float32Array(N), pb = new Float32Array(N), pa = new Float32Array(N);
                for (let p = 0, q = 0; p < N; p++, q += 4) {
                    const a = srcOrig[q + 3] / 255;
                    pr[p] = Math.pow(srcOrig[q] * a, gamma);
                    pg[p] = Math.pow(srcOrig[q + 1] * a, gamma);
                    pb[p] = Math.pow(srcOrig[q + 2] * a, gamma);
                    pa[p] = Math.pow(srcOrig[q + 3], gamma);
                }
                // Sommes-préfixes horizontales par ligne (→ somme d'un segment en O(1))
                const W1 = w + 1;
                const sr = new Float64Array(W1 * h), sg = new Float64Array(W1 * h), sb = new Float64Array(W1 * h), sa = new Float64Array(W1 * h);
                for (let y = 0; y < h; y++) {
                    const ro = y * W1, po = y * w;
                    for (let x = 0; x < w; x++) {
                        sr[ro + x + 1] = sr[ro + x] + pr[po + x];
                        sg[ro + x + 1] = sg[ro + x] + pg[po + x];
                        sb[ro + x + 1] = sb[ro + x] + pb[po + x];
                        sa[ro + x + 1] = sa[ro + x] + pa[po + x];
                    }
                }
                // Demi-largeur du disque pour chaque décalage vertical
                const halfW = new Int32Array(radius + 1);
                for (let dy = 0; dy <= radius; dy++) halfW[dy] = Math.floor(Math.sqrt(radius * radius - dy * dy));
                const img = new ImageData(new Uint8ClampedArray(srcOrig), w, h), d_ = img.data;
                const total = ey - sy || 1;
                for (let y = sy; y < ey; y++) {
                    if ((y - sy) % 24 === 0) this.reportProgress(Math.round(((y - sy) / total) * 100), "Flou d'objectif (bokeh)");
                    for (let x = 0; x < w; x++) {
                        let ar = 0, ag = 0, ab = 0, aacc = 0, cnt = 0;
                        for (let dy = -radius; dy <= radius; dy++) {
                            const yy = y + dy; if (yy < 0 || yy >= h) continue;
                            const hw = halfW[dy < 0 ? -dy : dy];
                            const x0 = x - hw < 0 ? 0 : x - hw;
                            const x1 = x + hw > w - 1 ? w - 1 : x + hw;
                            const ro = yy * W1;
                            ar += sr[ro + x1 + 1] - sr[ro + x0];
                            ag += sg[ro + x1 + 1] - sg[ro + x0];
                            ab += sb[ro + x1 + 1] - sb[ro + x0];
                            aacc += sa[ro + x1 + 1] - sa[ro + x0];
                            cnt += (x1 - x0 + 1);
                        }
                        if (cnt < 1) cnt = 1;
                        const o = (y * w + x) * 4;
                        const A = Math.pow(aacc / cnt, invG);   // alpha moyen (retour de l'espace lumière)
                        const inv = A > 0 ? 255 / A : 0;
                        d_[o] = Math.pow(ar / cnt, invG) * inv;
                        d_[o + 1] = Math.pow(ag / cnt, invG) * inv;
                        d_[o + 2] = Math.pow(ab / cnt, invG) * inv;
                        d_[o + 3] = A;
                    }
                }
                this.ctx.putImageData(img, 0, 0); return;
            }
            case 'vibrance': {
                // Booste surtout les couleurs peu saturées (protège les tons déjà vifs).
                const amount = val('ef-vibr') / 100;
                const img = new ImageData(new Uint8ClampedArray(srcOrig), w, h), d_ = img.data;
                const startIdx = sy * w * 4, endIdx = ey * w * 4, total = endIdx - startIdx || 1;
                for (let i = startIdx; i < endIdx; i += 4) {
                    if ((i - startIdx) % 160000 === 0) this.reportProgress(Math.round(((i - startIdx) / total) * 100), "Vibrance");
                    const r = srcOrig[i], g = srcOrig[i + 1], b = srcOrig[i + 2];
                    const mx = r > g ? (r > b ? r : b) : (g > b ? g : b);
                    const avg = (r + g + b) / 3;
                    const boost = amount * (1 - (mx - avg) / 255);
                    d_[i] = avg + (r - avg) * (1 + boost);
                    d_[i + 1] = avg + (g - avg) * (1 + boost);
                    d_[i + 2] = avg + (b - avg) * (1 + boost);
                }
                this.ctx.putImageData(img, 0, 0); return;
            }
            case 'unsharp': {
                // Masque flou : original + intensité × (original − flou), avec seuil anti-bruit.
                // Le flou est calculé sur toute la tuile (marge incluse) pour éviter les coutures.
                const amount = val('ef-us-amount') / 100;
                const radius = Math.max(1, Math.round(pxRad(val('ef-us-radius') || 3)));
                const thr = val('ef-us-threshold');
                const blur = new Uint8ClampedArray(srcOrig);
                this._boxBlurRGBA(blur, w, h, radius);
                const img = new ImageData(new Uint8ClampedArray(srcOrig), w, h), d_ = img.data;
                const startIdx = sy * w * 4, endIdx = ey * w * 4, total = endIdx - startIdx || 1;
                for (let i = startIdx; i < endIdx; i += 4) {
                    if ((i - startIdx) % 160000 === 0) this.reportProgress(Math.round(((i - startIdx) / total) * 100), "Masque flou");
                    for (let c = 0; c < 3; c++) {
                        const o = srcOrig[i + c];
                        const diff = o - blur[i + c];
                        if (diff > thr || diff < -thr) d_[i + c] = o + amount * diff;
                    }
                }
                this.ctx.putImageData(img, 0, 0); return;
            }
            case 'temptint': {
                // Balance des blancs simple : Température (bleu↔ambre) + Teinte (vert↔magenta)
                const t = (val('ef-tt-temp') || 0) * 0.6;
                const ti = (val('ef-tt-tint') || 0) * 0.6;
                const img = new ImageData(new Uint8ClampedArray(srcOrig), w, h), d_ = img.data;
                const startIdx = sy * w * 4, endIdx = ey * w * 4, total = endIdx - startIdx || 1;
                for (let i = startIdx; i < endIdx; i += 4) {
                    if ((i - startIdx) % 160000 === 0) this.reportProgress(Math.round(((i - startIdx) / total) * 100), "Température / Teinte");
                    let r = srcOrig[i] + t - ti * 0.5;
                    let g = srcOrig[i + 1] + ti;
                    let b = srcOrig[i + 2] - t - ti * 0.5;
                    d_[i] = r < 0 ? 0 : r > 255 ? 255 : r;
                    d_[i + 1] = g < 0 ? 0 : g > 255 ? 255 : g;
                    d_[i + 2] = b < 0 ? 0 : b > 255 ? 255 : b;
                }
                this.ctx.putImageData(img, 0, 0); return;
            }
            default: this.ctx.putImageData(new ImageData(new Uint8ClampedArray(srcOrig),w,h), 0,0); break;
        }

    }
};

self.onmessage = async function(e) {
    if (e.data.type === 'preview') {
        const d = e.data; FilterManager._startY=d.startY||0; FilterManager._endY=d.endY||d.h; FilterManager._margin=d.margin||0;
        Object.assign(vals, d.params); FilterManager.originalImageData = new ImageData(new Uint8ClampedArray(d.srcOrig),d.w,d.h);
        FilterManager.currentEffect=d.effect; FilterManager._jobId=d.jobId; FilterManager._effectPreviewPxScale=d.ps;
        if(typeof MasterPaintWasm!=='undefined'){
            MasterPaintWasm.setSettings({ wasmEnabled:d.wasmEnabled, webglEnabled:d.webglEnabled });
            if(d.wasmEnabled && !MasterPaintWasm.isLoaded) await MasterPaintWasm.init();
        }
        FilterManager._hsvMixParams=d.hsvMixParams||d.params?.hsvMixParams||null;
        FilterManager._cbParams=d.cbParams||d.params?.cbParams||null;
        currentImageData=null;
        try {
            FilterManager._previewOneTarget((id)=>{ 
                const v=vals[id]; if(v===undefined) return 0;
                if(typeof v==='string'&&v.includes(',')) return parseFloat(v.replace(',','.'))||0;
                return parseFloat(v)||0; 
            }, d.w, d.h, d);
        } catch(err){ self.postMessage({ jobId:d.jobId, error:err.toString() }); return; }
        if(currentImageData){
            let b=currentImageData.data.buffer; if(b===FilterManager.originalImageData.data.buffer) b=b.slice(0);
            self.postMessage({ jobId:d.jobId, buffer:b, w:d.w, h:d.h }, [b]);
        } else { self.postMessage({ jobId:d.jobId, error:'No data output' }); }
    }
};
